baseURL = "/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Pleroma"
subtitle = "Apps for Pleroma"

FootnoteReturnLinkContents = "↩"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  blog = "/:title/"

[author]
  name = ""

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  description = "Pleroma is a free, federated social networking server built on open protocols. It is compatible with GNU Social, Mastodon, and many other ActivityPub and OStatus implementations."
  OpenLinksInNewWindow = true

[outputs]
  home = ["html"]