[build]
  publish = "public"
  command = "npm run build"

# Config for Github pull requests.
[context.deploy-preview]
  command = "npm run development"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "development"

# Default config for branch deploys.
[context.branch-deploy]
  # Build without minification & optimization.
  command = "npm run development"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "development"

# Custom config for the staging branch.
[context.staging]
  # We want a production-like build.
  command = "npm run build"

[context.staging.environment]
  HUGO_ENV = "development"

# Production config.
[context.production]
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"